using System.Text.Json;
using System.Diagnostics;
using DiceGame.Core;
using DiceGame.App;

namespace DiceGame.SkillTests;
internal static class Program
{
    static readonly string Root=AppContext.BaseDirectory;
    static readonly GameData Data=GameData.FromDirectory(Path.Combine(Root,"Data"));
    static readonly GameData Legacy=GameData.FromDirectory(Path.Combine(Root,"LegacyBalanceData"));
    static readonly CampaignCatalog Catalog=new(Data,File.ReadAllText(Path.Combine(Root,"Data/campaign.json")));
    static readonly List<object> Results=[];
    static int Passed,Failed;
    static int Main()
    {
        Test("configuration: 16 slots / four columns / exactly six types",()=>{Eq(Data.Game.Board.Slots,16);Eq(Data.Game.Board.Columns,4);Eq(Data.Game.Rules.MinDeck,6);Eq(Data.Game.Rules.MaxDeck,6);Near(Data.Game.Rules.DamageScale,.5);});
        Test("deck: 0–5 entries and duplicate six are all rejected",()=>{for(int i=0;i<6;i++){Check(!Data.ValidDeck(Data.DefaultDeck.Take(i)));Throws(()=>new Simulation(Data,Data.DefaultDeck.Take(i)));}Check(!Data.ValidDeck(Enumerable.Repeat("pulse",6)));Check(Data.ValidDeck(Data.DefaultDeck));});
        Test("deck: future seventh registered type is selectable, not automatically carried",()=>{var dice=Data.Dice.Select(CampaignCatalog.Copy).ToList();var next=CampaignCatalog.Copy(dice[0]);next.Id="future";dice.Add(next);var skills=Data.Skills.Values.Select(CampaignCatalog.Copy).ToList();var set=CampaignCatalog.Copy(skills[0]);set.Type="future";skills.Add(set);var data=new GameData(Encode(Data.Game),Encode(dice),Encode(Data.Upgrades),Encode(skills));Check(data.ValidDeck(data.DefaultDeck.Take(5).Append("future")));Check(!data.ValidDeck(data.Dice.Select(d=>d.Id)));Eq(new Simulation(data).State.Deck.Count,6);});
        Test("deck: locked die still blocks a complete six-die launch",()=>{var p=new CampaignProgression(Catalog);var state=p.NewState();state.UnlockedDice.Remove("bank");Throws(()=>p.PrepareRun(state,"region_01",Data.DefaultDeck,10));Eq(state.NextRunSerial,1L);});
        Test("deck UI backend: cannot save or start five-type draft",()=>{var a=App();a.Action("editDeck");a.Action("deck:bank");Eq(a.EditingDeck.Count,5);Check(!a.SaveDeck());Eq(a.Deck.Count,6);});
        Test("economy: six distinct opening dice create early growth headroom",()=>{var old=new Simulation(Legacy,Data.DefaultDeck,5);var now=Sim();Eq(now.Count,6);Check(now.State.Board.Take(6).Select(d=>d!.Type).SequenceEqual(Data.DefaultDeck));double oldDps=old.State.Board.Where(d=>d!=null).Sum(d=>old.Stats(d!).Volley/old.Stats(d!).Reload),nowDps=now.State.Board.Where(d=>d!=null).Sum(d=>now.Stats(d!).Volley/now.Stats(d!).Reload);Check(nowDps/oldDps>.80&&nowDps/oldDps<.86);Near(now.SummonCost,10);});
        Test("damage budget: sixteen-slot board retains original full-board capacity",()=>{var old=new Simulation(Legacy,Data.DefaultDeck,1);var now=Sim();foreach(string type in Data.DefaultDeck)for(int p=1;p<=6;p++){var d=new DieState{Type=type,Pips=p};Near(now.Stats(d).Volley*16,old.Stats(d).Volley*8);}});
        Test("summoning: 16th slot reachable, 17th rejected without cost and price scales with crowding",()=>{var s=Sim();s.State.Energy=10000;Near(s.SummonCost,10);while(s.Count<8)Check(s.Summon().Ok);Near(s.SummonCost,12);while(s.Count<16)Check(s.Summon().Ok);double energy=s.State.Energy;Check(!s.Summon().Ok);Eq(s.State.Energy,energy);Check(s.State.Board[15]!=null);});
        Test("input: fourth row accepts summon and move",()=>{var a=App();a.StartExpedition();a.Sim!.State.Energy=1000;var p=Data.SlotPosition(15);a.OnDown(p.X,p.Y);a.OnUp(p.X,p.Y);Check(a.Sim.State.Board[15]!=null);var q=Data.SlotPosition(14);a.Sim.State.Board[14]=null;a.OnDown(p.X,p.Y);a.OnMove(q.X,q.Y);a.OnUp(q.X,q.Y);Check(a.Sim.State.Board[14]!=null&&a.Sim.State.Board[15]==null);});
        Test("level 2: no branch prompt, surge preserved",()=>{var s=Sim();Pair(s,1);Check(s.Merge(0,1).Ok);Eq(s.State.Board[1]!.Pips,2);Check(!s.AwaitingDiceSkill);Eq(s.State.PendingShots.Count,2);});
        foreach(string type in Data.DefaultDeck)
            Test("level 3: roll result before displaying only its skills / "+type,()=>{var s=Sim();MergeTo(s,3,type);Eq(s.CurrentSkillChoice!.DiceType,type);Eq(s.SkillOptions[0].Name,Data.Skills[type].Level3[0].Name);Eq(s.SkillOptions[1].Name,Data.Skills[type].Level3[1].Name);Eq(s.State.Board[1]!.Tier3,"");Eq(s.State.PendingShots.Count,0);Choose(s,"A");Check(!s.AwaitingDiceSkill);Eq(s.State.Board[1]!.Tier3,"A");Eq(s.State.PendingShots.Count,s.Stats(s.State.Board[1]!).Count);SaveCodec.ValidateRun(Data,s.ExportSave());});
        Test("instance scope: one die's branch does not upgrade another die",()=>{var s=Sim();MergeTo(s,3,"pulse");var other=s.MakeDie("pulse",3);other.Tier3="B";s.State.Board[2]=other;var before=s.Stats(other);Choose(s,"A");Near(s.Stats(other).Volley,before.Volley);Eq(other.Tier3,"B");});
        Test("4/5: inherit target A/B key and remap to random result type",()=>{foreach(int p in new[]{4,5}){var s=Sim();Pair(s,p-1);s.State.Board[0]!.Tier3="A";s.State.Board[1]!.Tier3="B";NextType(s,"frost");Check(s.Merge(0,1).Ok);var d=s.State.Board[1]!;Eq(d.Type,"frost");Eq(d.Tier3,"B");Check(!s.AwaitingDiceSkill);Near(s.Stats(d).SlowRadius,34);Eq(s.Stats(d).Count,p);SaveCodec.ValidateRun(Data,s.ExportSave());}});
        Test("6: old branch cleared; A/B then C/D for final type",()=>{var s=Sim();MergeTo(s,6,"blast");Eq(s.State.Board[1]!.Tier3,"");Eq(s.State.PendingSkills.Count,2);Eq(s.CurrentSkillChoice!.Tier,3);Check(!s.ChooseDiceSkill(s.CurrentSkillChoice.ChoiceId,"C"));Choose(s,"A");Eq(s.CurrentSkillChoice!.Tier,6);Eq(s.State.PendingShots.Count,0);Choose(s,"D");var d=s.State.Board[1]!;Eq(d.Tier3,"A");Eq(d.Tier6,"D");Check(!s.AwaitingDiceSkill);Near(s.Stats(d).BlastRadius,48*1.35);Near(s.Stats(d).BossDamageMultiplier,1.5);Eq(s.State.PendingShots.Count,6);});
        Test("double click: old token cannot consume the next choice",()=>{var s=Sim();MergeTo(s,6,"pulse");long token=s.CurrentSkillChoice!.ChoiceId;Check(s.ChooseDiceSkill(token,"B"));Check(!s.ChooseDiceSkill(token,"C"));Eq(s.CurrentSkillChoice!.Tier,6);Choose(s,"C");Check(!s.ChooseDiceSkill(token,"A"));Eq(s.State.Board[1]!.Tier3,"B");});
        Test("pending modal: freezes enemies, projectiles, energy and all board actions",()=>{var s=Sim();MergeTo(s,3,"arc");string before=Encode(s.ExportSave());s.Step(.1);Check(!s.Fire(-1.5).Ok&&!s.Summon().Ok&&!s.Move(1,2)&&!s.Recycle(1).Ok&&!s.Merge(0,1).Ok);s.AdvanceWave();s.OfferUpgrades();Check(!s.ChooseUpgrade("power"));Eq(Encode(s.ExportSave()),before);});
        Test("preview/choice: no reroll or mutation of random state",()=>{var s=Sim();MergeTo(s,6,"split");uint rng=s.Random.State;long die=s.State.Board[1]!.Id;string before=Encode(s.ExportSave());s.PreviewSkill(s.CurrentSkillChoice!.ChoiceId,"A");Eq(Encode(s.ExportSave()),before);Choose(s,"B");Choose(s,"C");Eq(s.Random.State,rng);Eq(s.State.Board[1]!.Id,die);});
        Test("snapshot: pre-existing shots do not change after branch choice",()=>{var s=Sim();s.Fire(-1.5);string shots=Encode(s.State.PendingShots);Pair(s,2,false);NextType(s,"pulse");Check(s.Merge(0,1).Ok);Choose(s,"B");Eq(Encode(s.State.PendingShots.Where(x=>!x.Snapshot.Surge)),shots);});
        Test("queue budget: merge reservation fails before consuming RNG or material",()=>{var s=Sim();Pair(s,2);var shot=new PendingShot();for(int i=0;i<1196;i++)s.State.PendingShots.Add(shot);uint rng=s.Random.State;Check(!s.Merge(0,1).Ok);Eq(s.Random.State,rng);Eq(s.Count,2);});
        Test("app: choice round-trip uses save candidate before publication",()=>{var store=new Store();var a=App(store);a.StartExpedition();MergeTo(a.Sim!,6,"bank");a.ConsumeEvents();Eq(a.Scene,"diceSkill");long q=a.Sim!.CurrentSkillChoice!.ChoiceId;store.Fail=true;Check(!a.ChooseDiceSkill(q,"B"));Eq(a.Sim.CurrentSkillChoice.ChoiceId,q);Eq(a.Sim.State.Board[1]!.Tier3,"");store.Fail=false;Check(a.ChooseDiceSkill(q,"B"));Eq(a.Scene,"diceSkill");var b=App(store);b.Resume();Eq(b.Scene,"diceSkill");Eq(b.Sim!.CurrentSkillChoice!.Tier,6);Eq(b.Sim.State.Board[1]!.Tier3,"B");Check(b.ChooseDiceSkill(b.Sim.CurrentSkillChoice.ChoiceId,"C"));Eq(b.Scene,"play");Eq(b.Sim.State.PendingShots.Count,6);});
        Test("app: town suspend and restart retain pending result and choice token",()=>{var store=new Store();var a=App(store);a.StartExpedition();MergeTo(a.Sim!,3,"frost");a.ConsumeEvents();var q=Encode(a.Sim!.CurrentSkillChoice!);Check(a.ReturnToTown());var b=App(store);b.Resume();Eq(b.Scene,"diceSkill");Eq(Encode(b.Sim!.CurrentSkillChoice!),q);});
        Test("event overflow cannot skip pending skill modal",()=>{var a=App();a.StartExpedition();MergeTo(a.Sim!,3,"bank");a.Sim!.Events.Clear();a.Scene="play";a.Tick(.01);Eq(a.Scene,"diceSkill");});
        Test("general wave upgrade and die choice do not overwrite each other",()=>{var a=App();a.StartExpedition();MergeTo(a.Sim!,3,"pulse");a.Sim!.State.AwaitingUpgrade=true;a.Sim.State.Offers=["power","reload","bounce"];a.ConsumeEvents();Check(a.ChooseDiceSkill(a.Sim.CurrentSkillChoice!.ChoiceId,"A"));Eq(a.Scene,"upgrade");Check(a.Sim.State.Offers.SequenceEqual(new[]{"power","reload","bounce"}));});
        Test("catalog: all registered branches and starter pairings produce finite bounded stats",()=>{var s=Sim();Eq(Data.Skills.Values.Sum(x=>x.Level3.Length+x.Level6.Length),Data.Dice.Length*4);foreach(var type in Data.DefaultDeck)foreach(string a in new[]{"A","B"})foreach(string b in new[]{"C","D"}){var q=s.Stats(Die(type,6,a,b));Check(double.IsFinite(q.Volley)&&q.Volley>0&&q.Reload>0&&q.Count<=18);Near(q.Damage*q.Count,q.Volley);Check(q.MaxBoost<=6&&q.Bounces<=36&&q.ChildCount<=10);}});
        Test("pulse B: extra projectiles redistribute volley, never multiply total damage",()=>{var s=Sim();var d=Die("pulse",3,"B");var q=s.Stats(d);Eq(q.Count,5);Near(q.Volley,13*4.24*.5*1.12);Near(q.Damage,q.Volley/5);s.State.Board=[..new DieState?[16]];s.State.Board[0]=d;Check(s.Fire(-1.5).Ok);Eq(s.State.PendingShots.Count,5);});
        Test("pulse C: actual swept collision pierces two enemies without reversing",()=>{var s=Empty();EnemyState a=Enemy(s,100,260),b=Enemy(s,100,220);s.Grid.Rebuild(s.State.Enemies);var p=Projectile(s,Die("pulse",6,"A","C"),100,300);s.MoveProjectile(p,.2);Check(a.Hp<a.MaxHp&&b.Hp<b.MaxHp);Check(p.Vy<0);Eq(p.PiercesLeft,0);});
        Test("pulse D: boss direct damage multiplier is 1.5",()=>{var s=Empty();var e=Enemy(s,100,200,"boss");var p=Projectile(s,Die("pulse",6,"A","D"));s.PrimaryHit(e,p);Near(e.MaxHp-e.Hp,p.Stats.Damage*1.5);});
        Test("blast C: direct kill emits one extra nonrecursive explosion",()=>{var s=Empty();var e=Enemy(s,100,200);e.Hp=1;var b=Enemy(s,120,200);s.Grid.Rebuild(s.State.Enemies);var p=Projectile(s,Die("blast",6,"B","C"));s.PrimaryHit(e,p);s.FlushDamage();Near(b.MaxHp-b.Hp,p.Stats.Damage*(p.Stats.SplashFactor+.45));Eq(s.Events.Count(x=>x.Type=="explosion"),2);});
        Test("arc C: unused links return damage to isolated primary",()=>{var s=Empty();var e=Enemy(s,100,200);s.Grid.Rebuild(s.State.Enemies);var p=Projectile(s,Die("arc",6,"A","C"));s.PrimaryHit(e,p);Near(e.MaxHp-e.Hp,p.Stats.Damage*(1+p.Stats.ChainCount*.2));});
        Test("arc D: frost synergy affects primary and chain targets",()=>{var s=Empty();EnemyState a=Enemy(s,100,200),b=Enemy(s,150,200);a.SlowUntil=b.SlowUntil=10;a.SlowFactor=b.SlowFactor=.5;s.Grid.Rebuild(s.State.Enemies);var p=Projectile(s,Die("arc",6,"A","D"));s.PrimaryHit(a,p);Near(a.MaxHp-a.Hp,p.Stats.Damage*1.45);Near(b.MaxHp-b.Hp,p.Stats.Damage*p.Stats.ChainFactor*1.45);});
        Test("frost: weaker area slow never replaces stronger slow",()=>{var s=Empty();var e=Enemy(s,100,200);s.Grid.Rebuild(s.State.Enemies);s.PrimaryHit(e,Projectile(s,Die("frost",3,"A")));Near(e.SlowFactor,.38);s.PrimaryHit(e,Projectile(s,Die("frost",3,"B")));Near(e.SlowFactor,.38);});
        Test("frost C: shatter only triggers on an already slowed target",()=>{var s=Empty();EnemyState a=Enemy(s,100,200),b=Enemy(s,125,200);s.Grid.Rebuild(s.State.Enemies);var p=Projectile(s,Die("frost",6,"A","C"));s.PrimaryHit(a,p);s.FlushDamage();Near(b.Hp,b.MaxHp);s.PrimaryHit(a,p);s.FlushDamage();Near(b.MaxHp-b.Hp,p.Stats.Damage*.3);});
        Test("frost D: slow reaches 60 units away but not 90",()=>{var s=Empty();EnemyState a=Enemy(s,100,200),b=Enemy(s,160,200),c=Enemy(s,190,200);s.Grid.Rebuild(s.State.Enemies);s.PrimaryHit(a,Projectile(s,Die("frost",6,"A","D")));Check(b.SlowUntil>0&&c.SlowUntil==0);});
        Test("boss slow floor remains 72 percent",()=>{var s=Empty();var e=Enemy(s,200,220,"boss");e.Speed=10;s.PrimaryHit(e,Projectile(s,Die("frost",6,"A","D")));double y=e.Y;s.AdvanceEnemies(.1);Near(e.Y-y,.72);});
        Test("split C: children get pierces, remain nonrecursive",()=>{var s=Empty();var e=Enemy(s,100,200);s.Grid.Rebuild(s.State.Enemies);var p=Projectile(s,Die("split",6,"A","C"));s.PrimaryHit(e,p);Eq(s.State.Projectiles.Count,p.Stats.ChildCount);Check(s.State.Projectiles.All(c=>c.PiercesLeft==2&&c.Child&&c.SplitDone));int count=s.State.Projectiles.Count;s.PrimaryHit(e,s.State.Projectiles[0]);Eq(s.State.Projectiles.Count,count);});
        Test("split D: child bounce and lifetime modifiers are applied",()=>{var s=Empty();var e=Enemy(s,100,200);var p=Projectile(s,Die("split",6,"B","D"));s.PrimaryHit(e,p);var c=s.State.Projectiles[0];Eq(c.Bounces,10);Near(c.Life,3.4+.8+1.5);});
        Test("bank C: retained wall bonus is half, not repeated full multiplier",()=>{var s=Empty();var e=Enemy(s,100,200);var p=Projectile(s,Die("bank",6,"A","C"));p.WallPower=3;s.PrimaryHit(e,p);Near(p.WallPower,2);s.PrimaryHit(e,p);Near(p.WallPower,1.5);});
        Test("bank D: shock uses only extra wall damage and never recurses",()=>{var s=Empty();EnemyState a=Enemy(s,100,200),b=Enemy(s,130,200);s.Grid.Rebuild(s.State.Enemies);var p=Projectile(s,Die("bank",6,"B","D"));p.WallPower=3;s.PrimaryHit(a,p);s.FlushDamage();Near(b.MaxHp-b.Hp,p.Stats.Damage*2*.45);Near(p.WallPower,1);Eq(s.State.DamageQueue.Count,0);});
        Test("saturation: split fallback queue is strictly bounded",()=>{var s=Empty();var e=Enemy(s,100,200);var d=Die("split",6,"A","D");while(s.State.Projectiles.Count<Data.Game.Rules.MaxProjectiles)s.State.Projectiles.Add(Projectile(s,d));for(int i=0;i<500;i++)s.PrimaryHit(e,Projectile(s,d));Check(s.State.PendingShots.Count<=Data.Game.Rules.MaxQueuedShots);});
        Test("save validation: wrong result ID/type/tier is rejected",()=>{var s=Sim();MergeTo(s,6,"pulse");var x=s.ExportSave();x.PendingSkills[0].DieId=999999;Throws(()=>Simulation.Restore(Data,x));x=s.ExportSave();x.PendingSkills[0].DiceType="blast";Throws(()=>Simulation.Restore(Data,x));x=s.ExportSave();x.PendingSkills[0].Tier=4;Throws(()=>Simulation.Restore(Data,x));});
        Test("save validation: missing branch or duplicate identity is rejected",()=>{var s=Sim();MergeTo(s,3,"pulse");Choose(s,"A");var x=s.ExportSave();x.Board[1]!.Tier3="";Throws(()=>Simulation.Restore(Data,x));x=s.ExportSave();x.Board[2]=x.Board[1]!.Copy();Throws(()=>Simulation.Restore(Data,x));});
        Test("save: skill and RNG continuation are deterministic",()=>{var s=Sim();MergeTo(s,6,"arc");Choose(s,"B");var b=Simulation.Restore(Data,s.ExportSave());Choose(s,"D");Choose(b,"D");for(int i=0;i<80;i++){s.Step(1d/120);b.Step(1d/120);}Eq(Encode(s.ExportSave()),Encode(b.ExportSave()));});
        Test("authoring: unknown modifier, missing branch and NaN fail validation",()=>{var text=File.ReadAllText(Path.Combine(Root,"Data/dice_skills.json"));Throws(()=>DiceSkillCatalog.Parse(text.Replace("damageMultiplier","damageMultipler")));var sets=Data.Skills.Values.Select(CampaignCatalog.Copy).ToArray();sets[0].Level3=[sets[0].Level3[0]];Throws(()=>DiceSkillCatalog.Parse(Encode(sets)));Throws(()=>new DiceSkillModifiers{DamageMultiplier=double.NaN}.Validate());});
        Test("authoring: active run pins skills instead of following live edits",()=>{var s=Sim();var d=Die("pulse",3,"A");double before=s.Stats(d).Volley;var mod=Data.Skills["pulse"].Level3[0].Modifiers;double keep=mod.DamageMultiplier;try{mod.DamageMultiplier=2;Near(s.Stats(d).Volley,before);Near(Simulation.Restore(Data,s.ExportSave()).Stats(d).Volley,before);}finally{mod.DamageMultiplier=keep;}});
        Test("migration: old two-type campaign expands without losing dice, money or lead",()=>{var store=OldSave();var env=SaveCodec.Decode(Data,store.Value!);Eq(env.Version,4);Eq(env.Deck.Count,6);Eq(env.Run!.Board.Length,16);Eq(env.Run.Board[0]!.Pips,6);Eq(env.Run.Board[1]!.Pips,3);Eq(env.Run.PendingSkills.Count,3);Eq(env.Run.PendingShots.Count,0);Eq(env.Run.Expedition!.LeadDice,"pulse");Check(env.Campaign!.UnlockedDice.SetEquals(Data.DefaultDeck));});
        Test("migration: old high-level dice select skills without free merge volleys",()=>{var store=OldSave();var a=App(store);Check(a.LoadProblem=="");a.Resume();while(a.Sim!.AwaitingDiceSkill){var q=a.Sim.CurrentSkillChoice!;Check(a.ChooseDiceSkill(q.ChoiceId,q.Tier==3?"A":"C"));}Eq(a.Sim.State.PendingShots.Count,0);Eq(a.Sim.State.Board[0]!.Tier6,"C");Eq(a.Sim.State.Board[1]!.Tier3,"A");});
        Test("migration: completed workshop gains mastery once only",()=>{var store=OldSave();var raw=SaveCodec.Decode(Legacy,store.Value!);raw.Campaign!.Buildings["arc_workshop"]=new BuildingState{Tile=1,Level=1};raw.Campaign.Blueprints.Add("arc_workshop");store.Value=SaveCodec.Encode(raw);var a=App(store);Check(a.LoadProblem=="");Near(a.Campaign!.Bonuses.DiceDamagePercent["arc"],.1);a.Save();var b=App(store);Near(b.Campaign!.Bonuses.DiceDamagePercent["arc"],.1);});
        Test("new format: corrupt five-die deck is rejected rather than silently filled",()=>{var a=App();a.StartExpedition();var env=new SaveEnvelope{Version=SaveCodec.CurrentVersion,Deck=Data.DefaultDeck.Take(5).ToList(),Run=a.Sim!.ExportSave(),Campaign=a.Campaign};Throws(()=>SaveCodec.Decode(Data,SaveCodec.Encode(env)));});
        Test("migration: terminal high-pip dice resolve missing skills when continued as endless",()=>
        {var s=Sim();s.State.Expedition=new ExpeditionState{Region=CampaignCatalog.Copy(Catalog.Regions["region_01"]),Outcome="victory",CanContinueEndless=true};s.State.Over=true;s.State.Board[0]!.Pips=6;var next=CampaignCatalog.Copy(s.State.Expedition);next.Endless=true;next.Outcome="";s.ContinueAsEndless(next);Eq(s.State.PendingSkills.Count,2);Choose(s,"B");Choose(s,"D");Eq(s.State.PendingShots.Count,0);Eq(s.State.Board[0]!.Tier3,"B");Eq(s.State.Board[0]!.Tier6,"D");});
        Test("headless stress: 16 six-pip skilled dice stay within object budgets",Stress);
        Directory.CreateDirectory("Artifacts");File.WriteAllText("Artifacts/skills-test-results.json",JsonSerializer.Serialize(new{passed=Passed,failed=Failed,tests=Results},new JsonSerializerOptions{WriteIndented=true}));
        Console.WriteLine($"\n{Passed} skill/board tests passed, {Failed} failed.");return Failed==0?0:1;
    }
    static void Stress()
    {
        var s=Empty();s.State.Health=12;for(int i=0;i<16;i++){var d=s.MakeDie(Data.DefaultDeck[i%6],6);d.Tier3=i%2==0?"A":"B";d.Tier6=i%3==0?"C":"D";s.State.Board[i]=d;}
        for(int i=0;i<56;i++){var e=Enemy(s,55+(i%7)*50,170+(i/7)*30);e.Hp=e.MaxHp=1e12;e.Speed=0;e.W=e.H=24;}
        s.Grid.Rebuild(s.State.Enemies);var watch=Stopwatch.StartNew();int maxP=0,maxQ=0;
        for(int i=0;i<1200;i++)
        {if(i%12==0)s.Fire(-1.5707963+Math.Sin(i*.03)*.6);s.Step(1d/120);maxP=Math.Max(maxP,s.State.Projectiles.Count);maxQ=Math.Max(maxQ,s.State.PendingShots.Count);Check(s.State.Projectiles.Count<=Data.Game.Rules.MaxProjectiles&&s.State.PendingShots.Count<=Data.Game.Rules.MaxQueuedShots);}
        watch.Stop();SaveCodec.ValidateRun(Data,s.ExportSave());Console.WriteLine($"STRESS: 1200 fixed steps / {watch.Elapsed.TotalMilliseconds:0} ms / max projectiles {maxP}, queued {maxQ}");
        File.WriteAllText("Artifacts/skills-stress.json",Encode(new{steps=1200,simulated_seconds=10,wall_milliseconds=watch.Elapsed.TotalMilliseconds,max_projectiles=maxP,max_pending=maxQ,scope="C# simulation only; no GPU/frame-rate claim"}));
    }
    static Simulation Sim()=>new(Data,Data.DefaultDeck,914);
    static Simulation Empty(){var s=Sim();s.State.Enemies.Clear();s.State.Projectiles.Clear();s.State.PendingShots.Clear();s.Events.Clear();return s;}
    static DieState Die(string type,int pips,string a="",string b="")=>new(){Id=10000,Type=type,Pips=pips,Tier3=a,Tier6=b};
    static EnemyState Enemy(Simulation s,double x,double y,string kind="normal")=>s.AddEnemy(new EnemyState{X=x,Y=y,W=20,H=20,Hp=1e6,Speed=0,Kind=kind,Wave=1});
    static ProjectileState Projectile(Simulation s,DieState d,double x=100,double y=300)=>s.MakeProjectile(x,y,-Math.PI/2,new ShotSnapshot{Type=d.Type,Pips=d.Pips,Stats=s.Stats(d)});
    static void Pair(Simulation s,int pips,bool clearShots=true)
    {Array.Clear(s.State.Board);s.State.Board[0]=s.MakeDie("pulse",pips);s.State.Board[1]=s.MakeDie("pulse",pips);if(pips>=3){s.State.Board[0]!.Tier3="A";s.State.Board[1]!.Tier3="B";}if(clearShots)s.State.PendingShots.Clear();s.State.PendingSkills.Clear();}
    static void NextType(Simulation s,string type)
    {var rng=new SeededRandom(s.Random.State);for(int i=0;i<1000;i++){uint before=rng.State;if(rng.Pick(s.State.Deck)==type){s.Random.State=before;return;}}throw new Exception("Cannot set test roll.");}
    static void MergeTo(Simulation s,int result,string type){Pair(s,result-1);NextType(s,type);Check(s.Merge(0,1).Ok);Eq(s.State.Board[1]!.Type,type);}
    static void Choose(Simulation s,string key){Check(s.ChooseDiceSkill(s.CurrentSkillChoice!.ChoiceId,key));}
    static GameApp App(Store? store=null)=>new(Data,store??new Store(),new Silent(),Catalog){NativeUi=true};
    static Store OldSave()
    {var catalog=new CampaignCatalog(Legacy,File.ReadAllText(Path.Combine(Root,"LegacyBalanceData/campaign.json")));var store=new Store();var a=new GameApp(Legacy,store,new Silent(),catalog);a.StartExpedition(9);a.Sim!.State.Board[0]!.Pips=6;a.Sim.State.Board[1]!.Pips=3;a.Save();return store;}
    static void Test(string name,Action body){try{body();Passed++;Results.Add(new{name,passed=true});Console.WriteLine("PASS "+name);}catch(Exception ex){Failed++;Results.Add(new{name,passed=false,error=ex.ToString()});Console.WriteLine("FAIL "+name+"\n"+ex);}}
    static void Check(bool value){if(!value)throw new Exception("assertion failed");}
    static void Eq<T>(T got,T want){if(!EqualityComparer<T>.Default.Equals(got,want))throw new Exception($"Expected {want}, got {got}");}
    static void Near(double got,double want){if(Math.Abs(got-want)>1e-7*Math.Max(1,Math.Abs(want)))throw new Exception($"Expected {want:R}, got {got:R}");}
    static void Throws(Action body){try{body();}catch{return;}throw new Exception("Expected rejection");}
    static string Encode<T>(T value)=>JsonSerializer.Serialize(value,GameData.JsonOptions);
    sealed class Store:IDesktopStorage{public string? Value;public bool Fail;public string? Read()=>Value;public uint NewSeed()=>914;public void Write(string s){if(Fail)throw new IOException("injected");Value=s;}}
    sealed class Silent:ISoundOutput{public bool Enabled{get;set;}public bool Music{get;set;}public void Unlock(){}public void Play(string kind,int variant=0){}public void Tick(double dt,bool active){}public void Suspend(){}}
}
