'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {Simulation,Config,TYPES,validDeck}=require('../src/simulation.js');
const M=require('../src/math.js');
const R=Config.game.rules,A=Config.game.arena;
const make=deck=>new Simulation({seed:7319,deck:deck||['pulse','blast','arc','frost','split','bank']});
const advance=(s,seconds)=>{for(let i=0;i<Math.round(seconds*120);i++){s.step(1/120);s.takeEvents();}};
function empty(s){s.enemies=[];s.projectiles=[];s.pendingShots=[];s.events=[];s.grid.rebuild([]);return s;}
function projectile(s,type='pulse',pips=1,x=216,y=450,a=-Math.PI/2){const d=s.makeDie(type,pips);return s.makeProjectile(x,y,a,{type,pips,stats:s.stats(d)});}
function enemy(s,params={}){return s.addEnemy({x:216,y:300,w:39,h:39,hp:1000,speed:0,kind:'normal',wave:1,...params});}

test('deck is 1–6 distinct registered types; board is exactly eight slots',()=>{const s=make();assert.equal(s.board.length,8);assert.ok(validDeck(['pulse']));for(const deck of [[],['pulse','pulse'],['unknown'],['pulse','blast','arc','frost','split','bank','pulse']])assert.throws(()=>make(deck));});
test('a legal merge consumes precisely two dice and creates one higher random in-deck die',()=>{const s=make(['pulse','frost']);const n=s.count(),r=s.merge(0,1);assert.ok(r.ok);assert.equal(s.board[0],null);assert.equal(s.board[1].pips,2);assert.ok(s.deck.includes(s.board[1].type));assert.equal(s.count(),n-1);assert.equal(s.pendingShots.length,2);assert.ok(s.pendingShots.every(q=>q.snapshot.surge));});
test('different types, different pips, invalid indices, and self merge are rejected without mutation',()=>{const s=make();for(const [a,b]of[[0,2],[0,0],[-1,1],[9,0],[.5,1]]){const before=s.exportSave();assert.equal(s.merge(a,b).ok,false);assert.deepEqual(s.exportSave(),before);}s.board[1].pips=2;assert.equal(s.merge(0,1).ok,false);});
test('six-point dice cannot merge past the configured cap',()=>{const s=make();s.board[0].pips=s.board[1].pips=6;assert.equal(s.canMerge(0,1),false);assert.equal(s.merge(0,1).ok,false);assert.equal(s.board[1].pips,6);});
test('full board and insufficient energy summons are atomic; recycling restores room',()=>{const s=make();for(let i=0;i<8;i++)s.board[i]=s.makeDie('pulse',1);const e=s.energy;assert.equal(s.summon().reason,'full');assert.equal(s.energy,e);assert.equal(s.recycle(5).amount,8);assert.equal(s.count(),7);s.energy=0;assert.equal(s.summon().reason,'energy');assert.equal(s.board[5],null);s.energy=24;assert.ok(s.summon().ok);assert.equal(s.energy,0);assert.equal(s.count(),8);});
test('moving a die does not merge or replace an occupied target',()=>{const s=make();const d=s.board[0];assert.equal(s.move(0,2),false);assert.equal(s.move(0,7),true);assert.equal(s.board[7],d);assert.equal(s.board[0],null);});
test('simulation never auto-fires on time advancement',()=>{const s=make();advance(s,8);assert.equal(s.shots,0);assert.equal(s.manualVolleys,0);assert.equal(s.pendingShots.length,0);});
test('a release fires all ready dice once and respects per-die cooldown',()=>{const s=make();assert.equal(s.fire(-Math.PI/2).dice,3);assert.equal(s.pendingShots.length,3);assert.equal(s.fire(-Math.PI/2).ok,false);advance(s,.68);assert.equal(s.fire(-Math.PI/2).dice,2);});
test('two-to-one upgrades trade 5–12% sustained direct fire for stronger volleys and freed capacity',()=>{const s=make();for(let p=1;p<6;p++){const a=s.stats(s.makeDie('pulse',p)),b=s.stats(s.makeDie('pulse',p+1));const ratio=(b.volley/b.reload)/(2*a.volley/a.reload);assert.ok(b.volley>2*a.volley);assert.ok(ratio>.88&&ratio<.96,`pips ${p}, ratio ${ratio}`);assert.ok(b.reload>a.reload);}});
test('in-flight and queued bullets preserve snapshots when source is merged or recycled',()=>{const s=make();s.fire(-1.9);advance(s,.15);assert.ok(s.projectiles.length);const old=s.projectiles[0],damage=old.stats.damage,type=old.type;s.merge(0,1);s.recycle(2);s.upgrades.power=5;assert.equal(old.stats.damage,damage);assert.equal(old.type,type);assert.ok(s.projectiles.includes(old));assert.ok(s.pendingShots.every(q=>q.snapshot.stats.damage>0));});
test('swept collision hits a block even when displacement crosses it in one tick',()=>{const s=empty(make()),e=enemy(s,{hp:100});s.grid.rebuild(s.enemies);const p=projectile(s,'pulse',1,216,500);p.vy=-2400;s.moveProjectile(p,.1);assert.ok(e.hp<100);assert.ok(p.vy>0);assert.equal(e.hp,87);});
test('contact does not deal repeated damage every frame',()=>{const s=empty(make()),e=enemy(s,{hp:100});s.grid.rebuild(s.enemies);const p=projectile(s,'pulse',1,216,324);s.projectiles=[p];for(let i=0;i<5;i++)s.moveProjectile(p,1/120);assert.equal(e.hp,87);});
test('wall reflection is finite and consumes the bounce budget',()=>{const s=empty(make()),p=projectile(s,'pulse',1,401,280,0.1);s.grid.rebuild([]);const b=p.bounces;s.moveProjectile(p,1/120);assert.ok(p.vx<0);assert.equal(p.bounces,b-1);assert.ok(Number.isFinite(p.x));});
test('a zero-displacement slab query and corner contacts cannot produce NaN',()=>{assert.equal(M.sweepAABB(0,0,0,0,{left:5,right:6,top:5,bottom:6}),null);const s=empty(make()),p=projectile(s,'pulse',1,A.left+3.6,A.top+3.6,-2.3);for(let i=0;i<100&&!p.dead;i++)s.moveProjectile(p,1/120);assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));});
test('returning bullets are reclaimed by the open bottom boundary',()=>{const s=empty(make()),p=projectile(s,'pulse',1,216,550,Math.PI/2);s.moveProjectile(p,.03);assert.equal(p.dead,true);});
test('split children cannot recursively split',()=>{const s=empty(make()),e=enemy(s);s.grid.rebuild(s.enemies);const p=projectile(s,'split',4,180,300,-1.5);s.primaryHit(e,p);const count=s.projectiles.length;assert.equal(count,3);for(const child of s.projectiles.slice())s.primaryHit(e,child);assert.equal(s.projectiles.length,count);assert.ok(s.projectiles.every(p=>p.child&&p.splitDone));});
test('secondary explosion damage cannot trigger projectile effects; volatile enemies die once',()=>{const s=empty(make());const e1=enemy(s,{x:150,hp:20,kind:'volatile'}),e2=enemy(s,{x:190,hp:8,kind:'volatile'}),e3=enemy(s,{x:226,hp:5});s.grid.rebuild(s.enemies);const start=s.energy;s.applyDamage(e1,100,'#fff');s.flushDamage();assert.equal(s.kills,3);const energy=s.energy;s.applyDamage(e1,100,'#fff');s.flushDamage();assert.equal(s.kills,3);assert.equal(s.energy,energy);assert.equal(energy-start,12);assert.equal(s.damageQueue.length,0);assert.ok(e2.dead&&e3.dead);});
test('lightning selects different nearby targets and never itself creates another lightning proc',()=>{const s=empty(make()),e=enemy(s,{x:170});enemy(s,{x:210});enemy(s,{x:250});s.grid.rebuild(s.enemies);const p=projectile(s,'arc',3);s.primaryHit(e,p);const arcs=s.events.filter(e=>e.type==='arc');assert.equal(arcs.length,2);assert.ok(s.enemies.every(e=>e.hp<1000));});
test('frost preserves a movement floor, including for bosses',()=>{const s=empty(make()),e=enemy(s,{kind:'boss',speed:10});s.grid.rebuild(s.enemies);s.primaryHit(e,projectile(s,'frost',6));const before=e.y;s.advanceEnemies(1);assert.ok(e.y-before>=7.1);assert.ok(e.y-before<10);});
test('lane queues prevent frozen blocks from being overlapped by followers',()=>{const s=empty(make());const front=enemy(s,{y:350,speed:0}),back=enemy(s,{y:308,speed:50});s.advanceEnemies(1);assert.ok(back.y+back.h/2<=front.y-front.h/2-3.99);});
test('bank shots accumulate bounded wall power and consume it on the next hit',()=>{const s=empty(make()),e=enemy(s);const p=projectile(s,'bank',1,401,280,0.1);s.grid.rebuild([]);s.moveProjectile(p,1/120);assert.ok(p.wallPower>1);s.primaryHit(e,p);assert.equal(p.wallPower,1);assert.ok(e.hp<1000-13);});
test('damage cannot reward the same dead enemy more than once',()=>{const s=empty(make()),e=enemy(s,{hp:1});s.applyDamage(e,10,'#fff');const energy=s.energy;s.applyDamage(e,10,'#fff');assert.equal(s.kills,1);assert.equal(s.energy,energy);});
test('upgrade offers match the deck, are unique, and pause time until a legal choice',()=>{const s=make(['pulse']);s.offerUpgrades();assert.equal(new Set(s.offers).size,3);for(const id of s.offers){const u=Config.upgrades.find(u=>u.id===id);assert.ok(!u.requires||u.requires==='pulse');assert.notEqual(id,'repair');}const before=s.time;s.step(.1);assert.equal(s.time,before);assert.equal(s.chooseUpgrade('not-offered'),false);const choice=s.offers[0];assert.ok(s.chooseUpgrade(choice));assert.equal(s.awaitingUpgrade,false);assert.equal(s.wave,2);assert.equal(s.chooseUpgrade(choice),false);});
test('wave difficulty grows and every fifth wave includes a boss',()=>{const s=empty(make());s.startWave(2);const low=Math.max(...s.enemies.map(e=>e.maxHp));s.enemies=[];s.startWave(10);const bosses=s.enemies.filter(e=>e.kind==='boss');assert.equal(bosses.length,1);assert.ok(bosses[0].hp>low*5);assert.ok(s.enemies.length<=R.maxEnemies);});
test('seeded save and restore continue bit-for-bit with active projectiles',()=>{const a=make();a.fire(-2.2);advance(a,.25);const b=Simulation.restore(a.exportSave());for(let i=0;i<800;i++){if(i%85===0){a.fire(-1.15);b.fire(-1.15);}a.step(1/120);b.step(1/120);}assert.deepEqual(a.exportSave(),b.exportSave());});
test('corrupt saves are rejected instead of inserting bad values into collision or board state',()=>{const s=make();const base=s.exportSave();for(const mutate of [x=>x.board.push(null),x=>x.health=-2,x=>x.board[0].pips=7,x=>x.waveTime=NaN,x=>x.deck=['bad'],x=>x.upgrades={hacked:1},x=>x.enemies[0].x=Infinity,x=>x.rng=0]){const v=structuredClone(base);mutate(v);assert.throws(()=>Simulation.restore(v));}});
test('invalid dt cannot destabilize simulation and all capped effects stay bounded',()=>{const s=make();for(const dt of[-1,NaN,Infinity,.5])assert.throws(()=>s.step(dt));for(let i=0;i<8;i++)s.board[i]=s.makeDie('split',6);s.energy=999;for(let i=0;i<2000&&!s.over;i++){if(s.awaitingUpgrade)s.chooseUpgrade(s.offers[0]);if(i%24===0)s.fire(-1.3);s.step(1/120);s.takeEvents();assert.ok(s.projectiles.length<=R.maxProjectiles);assert.ok(s.pendingShots.length<=R.maxQueuedShots);for(const p of s.projectiles)assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));}});
test('death is terminal and restart state is clean',()=>{const s=empty(make());s.health=1;enemy(s,{y:A.breach-19,speed:20});s.step(.1);assert.equal(s.over,true);const t=s.time;s.step(.1);assert.equal(s.time,t);assert.equal(s.fire(-1.5).ok,false);const fresh=make();assert.equal(fresh.health,R.maxHealth);assert.equal(fresh.wave,1);assert.equal(fresh.projectiles.length,0);});
test('late-game upgrades still offer three useful choices without uncapping fire frequency',()=>{const s=make(['pulse']);for(const u of Config.upgrades)s.upgrades[u.id]=u.max;s.offerUpgrades();assert.equal(s.offers.length,3);assert.ok(s.offers.every(id=>['power','income','surge'].includes(id)));assert.ok(!s.offers.includes('reload'));});
test('projectile saturation defers split children instead of erasing their damage',()=>{const s=empty(make()),e=enemy(s,{hp:1});s.grid.rebuild(s.enemies);s.projectiles=Array.from({length:R.maxProjectiles},()=>projectile(s));const p=projectile(s,'split',4);p.vx=-300;p.vy=300;s.primaryHit(e,p);assert.equal(s.pendingShots.length,3);assert.ok(s.pendingShots.every(q=>q.child));assert.ok(e.dead);Simulation.restore(s.exportSave());for(const shot of s.projectiles)shot.dead=true;s.step(.01);s.step(.01);assert.equal(s.pendingShots.length,0);assert.equal(s.projectiles.length,3);assert.ok(s.projectiles.every(q=>q.child&&q.splitDone));});
